# Setup config
# ------------
project_name: CompositeTasking
which_system: composite_tasking

# Data set & task palette config
# ------------------------------
img_size:
  - 256
  - 256
task_code_len: 20
palette_mode: rnd_4_mosaic
task_list:
  - parts
  - seg
  - normals
  - saliency 
  - edges 
  
# Model config    
# ------------
which_model: composite_tasking_net_v1

encoder_arch: resnet34
encoder_pre_trained: true
# TODO this is not used for now
decoder_arch: None

n_fc_z_map: 6
latent_w_dim: 128

#which_cond: task_composition_v1
which_cond: task_composition_v1
cond_cfg_txt: cond_batch1x1

skip_conv_ks: 1
dec_conv_ks: 3
net_output_ch: 3

# Training config    
# ---------------
optimizer: adam
lr: 0.001
lr_div_encoder: 100.0
lr_scheduler: step_lr
lr_scheduler_step: 35
lr_scheduler_gamma: 0.3
pl_grad_clip_val: 0.0
wd: 0.00001
sgd_momentum: 0.9
sgd_nesterov_momentum: true

pl_max_epochs: 100
pl_min_epochs: 100
pl_early_stop_patience: -1
b_size: 10
n_workers: 10

seg_l_w: 3.0
parts_l_w: 4.0
edges_l_w: 50.0
saliency_l_w: 8.0
normals_l_w: 4.0

seg_l_focal_gamma: 2.0

pl_benchmark: true
pl_precision: 32
pl_sync_batchnorm: true
pl_which_profiler: simple

pl_progress_bar_refresh_rate: 100
pl_log_every_n_steps: 100
pl_flush_logs_every_n_steps: 100
pl_check_val_every_n_epoch: 1
pl_limit_train_batches: 1.0
pl_limit_val_batches: 1.0

debug: false
message: This is a debugging configuration & experiment